name: CI

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: .\test.ps1
        working-directory: test
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup llvm
        if: matrix.os != 'windows-latest'
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 22
      - run: sudo chmod +x ./test/test.sh
      - shell: bash
        working-directory: test
        run: |
          export CC=clang
          export CXX=clang++
          ./test.sh
